"""
Property-based tests using Hypothesis.
Generates random test cases to find edge cases.
"""

import pytest

try:
    from hypothesis import HealthCheck, given, settings
    from hypothesis import strategies as st
    from hypothesis.extra.pandas import column, data_frames, range_indexes

    HYPOTHESIS_AVAILABLE = True
except ImportError:
    HYPOTHESIS_AVAILABLE = False
    pytest.skip("Hypothesis not installed", allow_module_level=True)

from unittest.mock import patch

import pandas as pd

from data_processing.data_core import clean_descriptions, process_dataframe


@pytest.mark.property
@pytest.mark.skipif(not HYPOTHESIS_AVAILABLE, reason="Hypothesis not installed")
class TestPropertyBasedDataCore:
    """Property-based tests for data_core module."""

    @given(
        prices=st.lists(
            st.floats(min_value=-10000, max_value=-0.01, allow_nan=False, allow_infinity=False),
            min_size=1,
            max_size=100,
        )
    )
    @settings(
        max_examples=50,
        deadline=None,
        suppress_health_check=[
            HealthCheck.function_scoped_fixture,
            HealthCheck.filter_too_much,
        ],
    )
    def test_process_dataframe_always_returns_dataframe(self, prices: list[float]) -> None:
        """Property: process_dataframe always returns a valid DataFrame.

        Given: a list of negative floats generated by Hypothesis
        When:  process_dataframe() is called with those prices in a DataFrame
        Then:  the result is a DataFrame with category and price columns and no more rows than the input
        """
        # Arrange
        transaction_count = len(prices)
        df = pd.DataFrame({
            "data": [f"transaction {i}" for i in range(transaction_count)],
            "price": [str(p) for p in prices],
            "month": [1] * transaction_count,
            "year": [2023] * transaction_count,
        })

        # Act
        with patch("data_processing.data_core.mappings", {}):
            result = process_dataframe(df)

        # Assert — properties that should always hold
        assert isinstance(result, pd.DataFrame)
        assert len(result) <= len(df)  # Can be filtered
        assert "category" in result.columns
        assert "price" in result.columns

    @given(
        data=data_frames(
            index=range_indexes(min_size=1, max_size=50),
            columns=[
                column("data", dtype=str, elements=st.text(min_size=1, max_size=100)),
                column(
                    "price",
                    dtype=str,
                    elements=st.from_regex(r"-?\d+\.?\d*", fullmatch=True),
                ),
                column("month", dtype=int, elements=st.integers(min_value=1, max_value=12)),
                column(
                    "year",
                    dtype=int,
                    elements=st.integers(min_value=2000, max_value=2030),
                ),
            ],
        )
    )
    @settings(max_examples=20, deadline=None)
    def test_clean_descriptions_preserves_row_count(self, data: pd.DataFrame) -> None:
        """Property: clean_descriptions preserves the number of rows.

        Given: a Hypothesis-generated DataFrame with arbitrary valid strings
        When:  clean_descriptions() is called
        Then:  the result has the same number of rows and columns as the input
        """
        # Arrange — via @given decorator
        result = clean_descriptions(data)

        # Assert
        assert len(result) == len(data)
        assert list(result.columns) == list(data.columns)

    @given(
        prices=st.lists(
            st.floats(min_value=-10000, max_value=-0.01, allow_nan=False, allow_infinity=False),
            min_size=1,
            max_size=50,
        )
    )
    @settings(
        max_examples=30,
        deadline=None,
        suppress_health_check=[HealthCheck.function_scoped_fixture],
    )
    def test_price_conversion_always_positive(self, prices: list[float]) -> None:
        """Property: All negative prices are converted to positive.

        Given: a list of negative floats generated by Hypothesis
        When:  process_dataframe() is called
        Then:  every price in the result is a positive float
        """
        # Arrange
        df = pd.DataFrame({
            "data": [f"test {i}" for i in range(len(prices))],
            "price": [str(p) for p in prices],
            "month": [1] * len(prices),
            "year": [2023] * len(prices),
        })

        # Act
        with patch("data_processing.data_core.mappings", {}):
            result = process_dataframe(df)

        # Assert
        for price in result["price"]:
            assert float(price) > 0

    @given(
        text=st.text(
            min_size=1,
            max_size=200,
            alphabet=st.characters(blacklist_categories=["Cs"]),
        )
    )
    @settings(max_examples=100, deadline=None)
    def test_clean_descriptions_handles_arbitrary_strings(self, text: str) -> None:
        """Property: clean_descriptions handles any valid string input.

        Given: an arbitrary non-surrogate string generated by Hypothesis
        When:  clean_descriptions() is called
        Then:  it does not crash and the data cell remains a string
        """
        # Arrange
        df = pd.DataFrame({"data": [text], "price": ["-10.0"], "month": [1], "year": [2023]})

        # Act
        result = clean_descriptions(df)

        # Assert
        assert len(result) == 1
        assert isinstance(result["data"].iloc[0], str)


@pytest.mark.property
@pytest.mark.skipif(not HYPOTHESIS_AVAILABLE, reason="Hypothesis not installed")
class TestPropertyBasedInvariants:
    """Tests for invariants that should always hold."""

    @given(
        df=data_frames(
            index=range_indexes(min_size=0, max_size=100),
            columns=[
                column("data", dtype=str),
                column("price", dtype=str),
                column("month", dtype=int),
                column("year", dtype=int),
            ],
        )
    )
    @settings(max_examples=30, deadline=None)
    def test_clean_descriptions_idempotent(self, df: pd.DataFrame) -> None:
        """Property: Applying clean_descriptions twice gives same result.

        Given: a Hypothesis-generated DataFrame (skipped if empty)
        When:  clean_descriptions() is applied twice in succession
        Then:  both results are identical (the function is idempotent)
        """
        # Arrange — via @given decorator
        if len(df) == 0:
            return

        # Act
        first_clean = clean_descriptions(df)
        second_clean = clean_descriptions(first_clean)

        # Assert
        pd.testing.assert_frame_equal(first_clean, second_clean)

    @given(count=st.integers(min_value=1, max_value=50))
    @settings(
        max_examples=20,
        deadline=None,
        suppress_health_check=[HealthCheck.function_scoped_fixture],
    )
    def test_column_order_consistency(self, count: int) -> None:
        """Property: Output columns are always in consistent order.

        Given: a DataFrame with a Hypothesis-generated number of rows
        When:  process_dataframe() is called
        Then:  columns are always in [month, year, price, category, data] order
        """
        # Arrange
        df = pd.DataFrame({
            "data": [f"test {i}" for i in range(count)],
            "price": ["-10.0"] * count,
            "month": [1] * count,
            "year": [2023] * count,
        })

        # Act
        with patch("data_processing.data_core.mappings", {}):
            result = process_dataframe(df)

        # Assert
        expected_columns = ["month", "year", "price", "category", "data"]
        assert list(result.columns) == expected_columns


@pytest.mark.property
@pytest.mark.skipif(not HYPOTHESIS_AVAILABLE, reason="Hypothesis not installed")
class TestPropertyBasedEdgeCases:
    """Property-based tests for edge cases."""

    @given(
        month=st.integers(min_value=1, max_value=12),
        year=st.integers(min_value=1900, max_value=2100),
    )
    @settings(
        max_examples=50,
        deadline=None,
        suppress_health_check=[HealthCheck.function_scoped_fixture],
    )
    def test_date_fields_preserve_values(self, month: int, year: int) -> None:
        """Property: Month and year values are preserved through processing.

        Given: Hypothesis-generated month and year integers
        When:  process_dataframe() is called
        Then:  the output row retains the original month and year values
        """
        # Arrange
        df = pd.DataFrame({"data": ["test"], "price": ["-10.0"], "month": [month], "year": [year]})

        # Act
        with patch("data_processing.data_core.mappings", {}):
            result = process_dataframe(df)

        # Assert
        if len(result) > 0:
            assert result["month"].iloc[0] == month
            assert result["year"].iloc[0] == year

    @given(price_str=st.from_regex(r"-\d+\.\d{2}", fullmatch=True))
    @settings(
        max_examples=100,
        deadline=None,
        suppress_health_check=[HealthCheck.function_scoped_fixture],
    )
    def test_price_format_handling(self, price_str: str) -> None:
        """Property: Various price formats are handled correctly.

        Given: a Hypothesis-generated negative decimal price string
        When:  process_dataframe() is called
        Then:  the result price equals the absolute value of the input within 0.01 tolerance
        """
        # Arrange
        df = pd.DataFrame({"data": ["test"], "price": [price_str], "month": [1], "year": [2023]})

        # Act
        with patch("data_processing.data_core.mappings", {}):
            result = process_dataframe(df)

        # Assert
        if len(result) > 0:
            result_price = float(result["price"].iloc[0])
            original_price = abs(float(price_str))
            assert abs(result_price - original_price) < 0.01
